//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseProject.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolesOperationPermission
    {
        public int Id { get; set; }
        public string RoleId { get; set; }
        public string ResourceName { get; set; }
        public Core.Common.Security.ResourceOperationEnum Operation { get; set; }
    }
}
