//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeMain
    {
        public CodeMain()
        {
            this.Code = new HashSet<Code>();
        }
    
        public string ID { get; set; }
        public string Name { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string LastModifyBy { get; set; }
        public Nullable<System.DateTime> LastModifyDate { get; set; }
    
        public virtual ICollection<Code> Code { get; set; }
    }
}
