//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Code
    {
        public int SN { get; set; }
        public string MainID { get; set; }
        public string Value { get; set; }
        public string Display { get; set; }
        public int OrderBy { get; set; }
    
        public virtual CodeMain CodeMain { get; set; }
    }
}
