//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOperationLog
    {
        public int Id { get; set; }
        public System.DateTime VisitDateTime { get; set; }
        public string UserId { get; set; }
        public string Area { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string RawUrl { get; set; }
        public string Resource { get; set; }
        public string ResourceName { get; set; }
        public Core.Common.Security.ResourceOperationEnum Operation { get; set; }
        public string IP { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
